orbs:
  android: circleci/android@2.0

jobs:
  build:
    executor:
      name: android/default
      tag: 33.0.2-node
    environment:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk
    steps:
      - checkout
      - run:
          name: Verify Java Version
          command: java -version
      - run:
          name: Build App
          command: ./gradlew build
